# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57e4b20998208568dcf47314e91b7414d4ba3d06ef4c2d54ea437c1f2d041d42fa5dfc57650b53076c6a0df638259edfd5c7145ea4f7fcc44d68f9ac02e265be

test:
  secret_key_base: c0f9f4cb18bcc5f45665ddd7875ad56131c7624b19258fe6feb1b87e863fd007ce07e76d398704226db98ec1cc6cfbcc85b2a80ca6c67f9d2db839c38cca2bf6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
